#!/bin/bash

# Development environment setup script
# Usage: ./scripts/setup-dev.sh

set -e

echo "🛠️ Setting up MindCoach development environment..."

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check system requirements
check_requirements() {
    log_info "Checking system requirements..."
    
    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is required but not installed"
        log_info "Install Docker: https://docs.docker.com/get-docker/"
        exit 1
    fi
    
    # Check Docker Compose
    if ! command -v docker-compose &> /dev/null; then
        log_error "Docker Compose is required but not installed"
        log_info "Install Docker Compose: https://docs.docker.com/compose/install/"
        exit 1
    fi
    
    # Check if Docker is running
    if ! docker info &> /dev/null; then
        log_error "Docker is not running. Please start Docker and try again."
        exit 1
    fi
    
    # Check Node.js (optional, for local development)
    if command -v node &> /dev/null; then
        NODE_VERSION=$(node --version)
        log_info "Node.js version: $NODE_VERSION"
    else
        log_warning "Node.js not found. You can still use Docker for development."
    fi
    
    # Check Python (optional, for local development)
    if command -v python3 &> /dev/null; then
        PYTHON_VERSION=$(python3 --version)
        log_info "Python version: $PYTHON_VERSION"
    else
        log_warning "Python3 not found. You can still use Docker for development."
    fi
    
    log_success "System requirements check completed"
}

# Create development environment file
create_dev_env() {
    log_info "Creating development environment configuration..."
    
    if [ ! -f ".env.dev" ]; then
        cat > .env.dev << EOF
# Development Environment Configuration
COMPOSE_PROJECT_NAME=mindcoach-dev

# Database
POSTGRES_PASSWORD=devpassword
DATABASE_URL=postgresql://postgres:devpassword@postgres-dev:5432/mindcoach_dev

# Redis
REDIS_URL=redis://redis-dev:6379/0

# Flask
SECRET_KEY=dev-secret-key-change-in-production
FLASK_ENV=development
FLASK_DEBUG=1

# Celery
CELERY_BROKER_URL=redis://redis-dev:6379/0
CELERY_RESULT_BACKEND=redis://redis-dev:6379/0

# API Keys (set your actual keys)
XAI_API_KEY=your-xai-api-key-here
GROK_API_URL=https://api.x.ai/v1

# CORS
CORS_ORIGINS=http://localhost:3000,http://localhost:8080

# Logging
LOG_LEVEL=DEBUG

# Development Tools
DEV_DASHBOARD_PORT=8080
PGADMIN_PORT=8081
REDIS_COMMANDER_PORT=8082
EOF
        log_success "Created .env.dev file"
        log_warning "Please update XAI_API_KEY in .env.dev with your actual API key"
    else
        log_info ".env.dev file already exists"
    fi
}

# Create development directories
create_directories() {
    log_info "Creating development directories..."
    
    directories=(
        "data"
        "users"
        "logs/frontend"
        "logs/backend"
        "logs/celery"
        "logs/postgres"
        "logs/redis"
        "logs/nginx"
        "logs/mock-api"
        "dev-mocks"
        "dev-tools/public"
    )
    
    for dir in "${directories[@]}"; do
        mkdir -p "$dir"
        log_info "Created directory: $dir"
    done
    
    log_success "Development directories created"
}

# Setup mock API data
setup_mock_api() {
    log_info "Setting up mock API data..."
    
    mkdir -p dev-mocks/mappings
    mkdir -p dev-mocks/__files
    
    # Create mock API mappings
    cat > dev-mocks/mappings/xai-api.json << 'EOF'
{
  "mappings": [
    {
      "request": {
        "method": "POST",
        "urlPattern": "/v1/chat/completions"
      },
      "response": {
        "status": 200,
        "headers": {
          "Content-Type": "application/json"
        },
        "jsonBody": {
          "id": "chatcmpl-mock-{{randomValue length=10 type='ALPHANUMERIC'}}",
          "object": "chat.completion",
          "created": "{{now}}",
          "model": "grok-3-mini",
          "choices": [
            {
              "index": 0,
              "message": {
                "role": "assistant",
                "content": "This is a mock response for development. The actual content would be generated by Grok-3 Mini."
              },
              "finish_reason": "stop"
            }
          ],
          "usage": {
            "prompt_tokens": 50,
            "completion_tokens": 20,
            "total_tokens": 70
          }
        }
      }
    }
  ]
}
EOF
    
    log_success "Mock API data created"
}

# Setup database initialization
setup_database() {
    log_info "Setting up development database initialization..."
    
    cat > postgres/init-dev.sql << 'EOF'
-- Development database initialization

-- Create development users
CREATE USER dev_user WITH PASSWORD 'devpassword';
GRANT ALL PRIVILEGES ON DATABASE mindcoach_dev TO dev_user;

-- Create test data
INSERT INTO users (user_id, email) VALUES 
('dev-user-1', 'dev1@mindcoach.com'),
('dev-user-2', 'dev2@mindcoach.com'),
('test-user-1', 'test1@mindcoach.com')
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO subscriptions (user_id, subject, status) VALUES 
('dev-user-1', 'python', 'active'),
('dev-user-1', 'javascript', 'active'),
('dev-user-2', 'react', 'active')
ON CONFLICT (user_id, subject) DO NOTHING;

-- Enable query logging for development
ALTER SYSTEM SET log_statement = 'all';
ALTER SYSTEM SET log_min_duration_statement = 0;

SELECT pg_reload_conf();
EOF
    
    log_success "Database initialization setup completed"
}

# Setup pgAdmin configuration
setup_pgadmin() {
    log_info "Setting up pgAdmin configuration..."
    
    mkdir -p dev-tools
    
    cat > dev-tools/pgadmin-servers.json << 'EOF'
{
  "Servers": {
    "1": {
      "Name": "MindCoach Development",
      "Group": "Servers",
      "Host": "postgres-dev",
      "Port": 5432,
      "MaintenanceDB": "mindcoach_dev",
      "Username": "postgres",
      "Password": "devpassword",
      "SSLMode": "prefer",
      "SSLCert": "<STORAGE_DIR>/.postgresql/postgresql.crt",
      "SSLKey": "<STORAGE_DIR>/.postgresql/postgresql.key",
      "SSLCompression": 0,
      "Timeout": 10,
      "UseSSHTunnel": 0,
      "TunnelHost": "",
      "TunnelPort": "22",
      "TunnelUsername": "",
      "TunnelAuthentication": 0
    }
  }
}
EOF
    
    log_success "pgAdmin configuration created"
}

# Create development scripts
create_dev_scripts() {
    log_info "Creating development helper scripts..."
    
    # Start development environment
    cat > scripts/dev-start.sh << 'EOF'
#!/bin/bash
echo "🚀 Starting MindCoach development environment..."

# Load environment variables
if [ -f .env.dev ]; then
    export $(cat .env.dev | grep -v '^#' | xargs)
fi

# Start development services
docker-compose -f docker-compose.dev.yml up -d

echo "✅ Development environment started!"
echo ""
echo "🌐 Services:"
echo "  Frontend:          http://localhost:3000"
echo "  Backend API:       http://localhost:5000"
echo "  Development Dashboard: http://localhost:8080"
echo "  pgAdmin:           http://localhost:8081 (dev@mindcoach.com / devpassword)"
echo "  Redis Commander:   http://localhost:8082 (dev / devpassword)"
echo ""
echo "🔧 Debugging:"
echo "  Backend Debug Port: 5678 (VS Code/PyCharm)"
echo ""
echo "📋 Useful commands:"
echo "  View logs:         docker-compose -f docker-compose.dev.yml logs -f [service]"
echo "  Stop services:     docker-compose -f docker-compose.dev.yml down"
echo "  Restart service:   docker-compose -f docker-compose.dev.yml restart [service]"
EOF
    
    # Stop development environment
    cat > scripts/dev-stop.sh << 'EOF'
#!/bin/bash
echo "🛑 Stopping MindCoach development environment..."

docker-compose -f docker-compose.dev.yml down

echo "✅ Development environment stopped!"
EOF
    
    # Reset development environment
    cat > scripts/dev-reset.sh << 'EOF'
#!/bin/bash
echo "🔄 Resetting MindCoach development environment..."

# Stop and remove containers
docker-compose -f docker-compose.dev.yml down -v

# Remove development data
rm -rf data/* users/* logs/*

# Restart environment
./scripts/dev-start.sh

echo "✅ Development environment reset completed!"
EOF
    
    # Make scripts executable
    chmod +x scripts/dev-start.sh scripts/dev-stop.sh scripts/dev-reset.sh
    
    log_success "Development scripts created"
}

# Create VS Code configuration
create_vscode_config() {
    log_info "Creating VS Code development configuration..."
    
    mkdir -p .vscode
    
    # Launch configuration
    cat > .vscode/launch.json << 'EOF'
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}/backend",
                    "remoteRoot": "/app"
                }
            ],
            "justMyCode": false
        },
        {
            "name": "Debug Frontend",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/frontend/node_modules/.bin/react-scripts",
            "args": ["start"],
            "env": {
                "BROWSER": "none"
            },
            "cwd": "${workspaceFolder}/frontend"
        }
    ]
}
EOF
    
    # Tasks configuration
    cat > .vscode/tasks.json << 'EOF'
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Start Dev Environment",
            "type": "shell",
            "command": "./scripts/dev-start.sh",
            "group": "build",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            }
        },
        {
            "label": "Stop Dev Environment",
            "type": "shell",
            "command": "./scripts/dev-stop.sh",
            "group": "build",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            }
        },
        {
            "label": "Reset Dev Environment",
            "type": "shell",
            "command": "./scripts/dev-reset.sh",
            "group": "build",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            }
        },
        {
            "label": "View Logs",
            "type": "shell",
            "command": "docker-compose",
            "args": ["-f", "docker-compose.dev.yml", "logs", "-f"],
            "group": "test",
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared"
            }
        }
    ]
}
EOF
    
    # Settings
    cat > .vscode/settings.json << 'EOF'
{
    "python.defaultInterpreterPath": "./backend/venv/bin/python",
    "python.linting.enabled": true,
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.formatting.provider": "black",
    "python.testing.pytestEnabled": true,
    "python.testing.pytestArgs": [
        "backend/tests"
    ],
    "eslint.workingDirectories": ["frontend"],
    "editor.formatOnSave": true,
    "files.exclude": {
        "**/node_modules": true,
        "**/__pycache__": true,
        "**/venv": true,
        "**/logs": true,
        "**/data": true
    },
    "docker.defaultRegistryPath": "ghcr.io/mindcoach"
}
EOF
    
    # Extensions recommendations
    cat > .vscode/extensions.json << 'EOF'
{
    "recommendations": [
        "ms-python.python",
        "ms-python.flake8",
        "ms-python.black-formatter",
        "ms-vscode.vscode-typescript-next",
        "bradlc.vscode-tailwindcss",
        "ms-vscode.vscode-docker",
        "ms-vscode.vscode-json",
        "redhat.vscode-yaml",
        "esbenp.prettier-vscode",
        "ms-vscode.vscode-eslint"
    ]
}
EOF
    
    log_success "VS Code configuration created"
}

# Create development documentation
create_dev_docs() {
    log_info "Creating development documentation..."
    
    cat > docs/DEVELOPMENT_SETUP.md << 'EOF'
# Development Environment Setup

This guide will help you set up the MindCoach development environment using Docker.

## Prerequisites

- Docker Desktop (latest version)
- Docker Compose (included with Docker Desktop)
- Git
- VS Code (recommended)

## Quick Start

1. **Clone the repository**
   ```bash
   git clone <repository-url>
   cd mindcoach
   ```

2. **Run the setup script**
   ```bash
   ./scripts/setup-dev.sh
   ```

3. **Start the development environment**
   ```bash
   ./scripts/dev-start.sh
   ```

4. **Access the applications**
   - Frontend: http://localhost:3000
   - Backend API: http://localhost:5000
   - Development Dashboard: http://localhost:8080
   - pgAdmin: http://localhost:8081
   - Redis Commander: http://localhost:8082

## Development Workflow

### Hot Reloading

Both frontend and backend support hot reloading:

- **Frontend**: Changes to React components are automatically reflected
- **Backend**: Changes to Python files trigger automatic server restart
- **Celery Workers**: Automatically restart when code changes

### Debugging

#### Backend Debugging (Python)

1. The backend runs with debugpy on port 5678
2. Use VS Code's "Python: Remote Attach" configuration
3. Set breakpoints in your Python code
4. Attach the debugger and debug normally

#### Frontend Debugging

1. Use browser developer tools
2. Or use VS Code's "Debug Frontend" configuration
3. React Developer Tools extension is recommended

### Database Access

#### pgAdmin
- URL: http://localhost:8081
- Email: dev@mindcoach.com
- Password: devpassword

#### Direct PostgreSQL Connection
- Host: localhost
- Port: 5433
- Database: mindcoach_dev
- Username: postgres
- Password: devpassword

### Redis Access

#### Redis Commander
- URL: http://localhost:8082
- Username: dev
- Password: devpassword

#### Direct Redis Connection
- Host: localhost
- Port: 6380

### Development Dashboard

The development dashboard at http://localhost:8080 provides:

- Service status monitoring
- Real-time metrics
- File change notifications
- Log viewing
- Service management (start/stop/restart)

## Useful Commands

### Docker Compose Commands

```bash
# View logs for all services
docker-compose -f docker-compose.dev.yml logs -f

# View logs for specific service
docker-compose -f docker-compose.dev.yml logs -f backend-dev

# Restart a service
docker-compose -f docker-compose.dev.yml restart backend-dev

# Stop all services
docker-compose -f docker-compose.dev.yml down

# Stop and remove volumes (reset data)
docker-compose -f docker-compose.dev.yml down -v
```

### Development Scripts

```bash
# Start development environment
./scripts/dev-start.sh

# Stop development environment
./scripts/dev-stop.sh

# Reset development environment (removes all data)
./scripts/dev-reset.sh
```

### Testing

```bash
# Run backend tests
docker-compose -f docker-compose.dev.yml exec backend-dev python -m pytest

# Run frontend tests
docker-compose -f docker-compose.dev.yml exec frontend-dev npm test

# Run integration tests
python comprehensive-integration-test.py
```

## Configuration

### Environment Variables

Development environment variables are stored in `.env.dev`:

- Database credentials
- API keys
- Service ports
- Debug settings

### API Keys

Update the following in `.env.dev`:

```bash
XAI_API_KEY=your-actual-api-key
GROK_API_URL=https://api.x.ai/v1
```

## Troubleshooting

### Common Issues

1. **Port conflicts**: Change ports in `.env.dev` if needed
2. **Permission issues**: Ensure Docker has proper permissions
3. **Memory issues**: Increase Docker memory allocation
4. **Hot reloading not working**: Check file watching limits

### Reset Environment

If you encounter issues, reset the environment:

```bash
./scripts/dev-reset.sh
```

### View Service Status

Check the development dashboard or use:

```bash
docker-compose -f docker-compose.dev.yml ps
```

## VS Code Integration

The repository includes VS Code configuration for:

- Python debugging
- Task definitions
- Extension recommendations
- Workspace settings

Open the project in VS Code and install recommended extensions.

## File Structure

```
mindcoach/
├── backend/                 # Flask backend
├── frontend/               # React frontend
├── dev-tools/              # Development dashboard
├── scripts/                # Development scripts
├── docs/                   # Documentation
├── docker-compose.dev.yml  # Development services
├── .env.dev               # Development environment
└── .vscode/               # VS Code configuration
```

## Next Steps

1. Explore the codebase
2. Make changes and see hot reloading in action
3. Use the development dashboard to monitor services
4. Set up debugging in your IDE
5. Run tests to ensure everything works

Happy coding! 🚀
EOF
    
    log_success "Development documentation created"
}

# Main setup process
main() {
    log_info "Starting development environment setup..."
    
    check_requirements
    create_dev_env
    create_directories
    setup_mock_api
    setup_database
    setup_pgadmin
    create_dev_scripts
    create_vscode_config
    create_dev_docs
    
    log_success "🎉 Development environment setup completed!"
    
    echo ""
    log_info "Next steps:"
    echo "1. Update XAI_API_KEY in .env.dev with your actual API key"
    echo "2. Run: ./scripts/dev-start.sh"
    echo "3. Open http://localhost:8080 for the development dashboard"
    echo "4. Open the project in VS Code for the best development experience"
    echo ""
    log_info "Documentation: docs/DEVELOPMENT_SETUP.md"
}

# Run main function
main "$@"